FROM node:14.1-alpine as builder

WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm rebuild node-sass
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

COPY . .

CMD [ "npm", "start" ]
